// <auto-generated />
using System;
using HRSM.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HRSM.Migrations
{
    [DbContext(typeof(HRSMDbContext))]
    [Migration("20250415145059_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("HRSM.Models.Booking", b =>
                {
                    b.Property<int>("BookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("BOOKING_ID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("BookingId"));

                    b.Property<bool>("AirportTransfer")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("AIRPORT_TRANSFER");

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("BOOKING_DATE");

                    b.Property<string>("BookingType")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("BOOKING_TYPE");

                    b.Property<DateTime>("CheckInDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CHECK_IN_DATE");

                    b.Property<DateTime>("CheckOutDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CHECK_OUT_DATE");

                    b.Property<int>("ExtraBeds")
                        .HasColumnType("int")
                        .HasColumnName("EXTRA_BEDS");

                    b.Property<int>("ExtraRooms")
                        .HasColumnType("int")
                        .HasColumnName("EXTRA_ROOMS");

                    b.Property<int>("NumAdults")
                        .HasColumnType("int")
                        .HasColumnName("NUM_ADULTS");

                    b.Property<int>("NumChildren")
                        .HasColumnType("int")
                        .HasColumnName("NUM_CHILDREN");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("PAYMENT_METHOD");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("PAYMENT_STATUS");

                    b.Property<string>("ReservationNumber")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("RESERVATION_NUMBER");

                    b.Property<string>("RoomNumber")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("ROOM_NUMBER");

                    b.Property<decimal>("RoomRate")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("ROOM_RATE");

                    b.Property<bool>("RoomService")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("ROOM_SERVICE");

                    b.Property<string>("RoomType")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("ROOM_TYPE");

                    b.Property<bool>("SpaService")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("SPA_SERVICE");

                    b.Property<string>("SpecialRequests")
                        .HasColumnType("longtext")
                        .HasColumnName("SPECIAL_REQUESTS");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("STATUS");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("TOTAL_AMOUNT");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("USER_ID");

                    b.HasKey("BookingId");

                    b.HasIndex("UserId");

                    b.ToTable("BOOKING", (string)null);
                });

            modelBuilder.Entity("HRSM.Models.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ROOM_ID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("LastCleaned")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("LAST_CLEANED");

                    b.Property<DateTime?>("NextCleaning")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("NEXT_CLEANING");

                    b.Property<string>("Notes")
                        .HasColumnType("longtext")
                        .HasColumnName("NOTES");

                    b.Property<string>("RoomNumber")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("ROOM_NUMBER");

                    b.Property<string>("RoomType")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("ROOM_TYPE");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("STATUS");

                    b.HasKey("Id");

                    b.HasIndex("RoomNumber")
                        .IsUnique();

                    b.ToTable("ROOM", (string)null);
                });

            modelBuilder.Entity("HRSM.Models.User", b =>
                {
                    b.Property<int>("User_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("USER_ID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("User_Id"));

                    b.Property<string>("Contact")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("CONTACT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("FIRST_NAME");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("LAST_NAME");

                    b.Property<DateTime>("MemberSince")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("MEMBER_SINCE");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("PASSWORD");

                    b.Property<string>("ProfilePicturePath")
                        .HasColumnType("longtext")
                        .HasColumnName("PROFILE_PICTURE_PATH");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("ROLE");

                    b.HasKey("User_Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("USER", (string)null);
                });

            modelBuilder.Entity("HRSM.Models.Booking", b =>
                {
                    b.HasOne("HRSM.Models.User", "User")
                        .WithMany("Bookings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HRSM.Models.User", b =>
                {
                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
